apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
  namespace: edge-system
data:
  keepalived.conf: |
    vrrp_instance VI_1 {
      state BACKUP
      interface eth0
      virtual_router_id 51
      priority 100
      advert_int 1
      authentication {
        auth_type PASS
        auth_pass edu123
      }
      virtual_ipaddress {
        192.168.49.240/24
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: edge-system
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      hostNetwork: true
      serviceAccountName: default
      initContainers:
        - name: prepare-keepalived-assets
          image: osixia/keepalived:2.0.20
          command:
            - /bin/sh
            - -c
            - cp -R /container/service/keepalived/assets/* /config/ && cp /config-src/keepalived.conf /config/keepalived.conf
          volumeMounts:
            - name: config-src
              mountPath: /config-src
            - name: config
              mountPath: /config
      containers:
        - name: keepalived
          image: osixia/keepalived:2.0.20
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BROADCAST
                - NET_RAW
          volumeMounts:
            - name: config
              mountPath: /container/service/keepalived/assets
      volumes:
        - name: config-src
          configMap:
            name: keepalived-config
        - name: config
          emptyDir: {}
