global:
  imageTag: ""

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: localhost:62682/programming-edu/user-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources: {}

env: {}

extraEnvFrom: []
