apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "65.8.1"
    helm:
      valuesObject:
        defaultRules:
          create: true
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 256Mi
        grafana:
          adminPassword: admin
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: ALL
        prometheus:
          prometheusSpec:
            retention: 3d
            scrapeInterval: 30s
            replicas: 1
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
            additionalScrapeConfigs:
              - job_name: kafka-strimzi
                static_configs:
                  - targets:
                      - kafka-kafka-brokers.kafka.svc.cluster.local:9404
              - job_name: envoy-ratelimit
                static_configs:
                  - targets:
                      - ratelimit.ratelimit.svc.cluster.local:8080
        prometheusOperator:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
        nodeExporter:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
