version: '3'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn user_service.app.setup.app:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    env_file:
      .env
    networks:
      - shared_network
    ports:
      - $APP_PORT:8000

networks:
  shared_network:
    external: true