apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-service-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: user-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/user-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: task-service-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: task-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/task-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: submission-service-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: submission-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/submission-service
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/api-gateway
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agent-service-secrets
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: agent-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/agent-service
