apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: ratelimit-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.0
          ports:
            - containerPort: 6379
              name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: ratelimit-system
spec:
  selector:
    app: valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
